name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Se activa cuando se crea un tag como v1.0.1

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3

      - name: Checkout backend
        run: |
          cd ..
          git clone https://github.com/woodyjacques/GymDesk-backend.git
        shell: powershell

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias del desktop
        run: npm install
        working-directory: .

      - name: Instalar dependencias del backend
        run: npm install
        working-directory: ../GymDesk-backend

      - name: Compilar backend
        run: npm run build
        working-directory: ../GymDesk-backend

      - name: Crear carpeta data si no existe
        run: |
          if (-not (Test-Path "../GymDesk-backend/data")) {
            New-Item -ItemType Directory -Path "../GymDesk-backend/data"
          }
        shell: powershell

      - name: Build y Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
